name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Trigger only when index.html is changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Uploads the root directory (make sure index.html is here)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
